steps:
  # Build the container image
  - name: 'gcr.io/kaniko-project/executor:slim'
    args:
      - --destination=gcr.io/negainoido-icfpc2023/fastapi:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=24h
      - --context=dir://webapp/fastapi/
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fastapi'
      - '--image'
      - 'gcr.io/negainoido-icfpc2023/fastapi:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
