steps:
  # Build the container image
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/negainoido-icfpc2023/streamlit:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=24h
      - --context=dir://webapp/streamlit/
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_DEPLOY_TARGET'
      - '--image'
      - 'gcr.io/negainoido-icfpc2023/streamlit:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
images:
  - 'gcr.io/negainoido-icfpc2023/streamlit:$COMMIT_SHA'
