on:
  workflow_dispatch:
    inputs:
      solver: 
        required: true
        default: random
        type: choice
        options:
          - random
          - random2
          - random_exact

jobs:
  eval-batch:
    permissions:
      checks: write
    runs-on: [self-hosted, linux, x64]
    defaults:
      run:
        working-directory: ./solver
    steps:
      - uses: actions/checkout@v3
      - name: Print env variables
        run: printenv
      - name: Print gcloud accounts
        run: gcloud auth list
      - name: cargo build 
        run: cargo build --release
      - name: run batch
        id: batch
        env:
          PNUM: 4
        run: |
          bash ../tools/eval_batch.sh ${{ inputs.solver }} ${{ github.sha }}
          echo report=$(cat output/summary.json) >> ${GITHUB_OUTPUT}
      - uses: LouisBrunner/checks-action@v1.6.1
        if: always()
        with:
          token: ${{ github.token }}
          name: Batch Report ${{ inputs.solver }}
          conclusion: ${{ job.status }}
          output: ${{ steps.batch.outputs.report }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: submissions
          path: ${{ github.workspace }}/output
