on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Print env variables
        run: printenv
      - name: Print gcloud accounts
        run: gcloud auth list
