  on:
    push:
      branches: [main]
      paths:
        - 'solver/**'
    pull_request:
      branches:  [main]
      paths:
        - 'solver/**'
  jobs:
    build:
      runs-on: ubuntu-22.04
      defaults:
        run:
          working-directory: ./solver
      steps:
        - uses: actions/checkout@v3
        - uses: dtolnay/rust-toolchain@stable
        - uses: Swatinem/rust-cache@v2
          with:
            workspaces: "./solver -> target"
        - run: cargo test
    build-wasm:
      runs-on: ubuntu-22.04
      defaults:
        run:
          working-directory: ./solver
      env:
        CARGO_REGISTRIES_CRATES_IO_PROTOCOL: "sparse"
      steps:
        - uses: actions/checkout@v3
        - uses: dtolnay/rust-toolchain@stable
        - uses: Swatinem/rust-cache@v2
          with:
            prefix-key: "wasm-"
            workspaces: "./solver -> target"
        - run: |
            rustup component add rust-src
            cargo install wasm-pack
        - run: make wasm
