  on:
    push:
      branches: [main]
      paths:
        - 'solver/**'
    pull_request:
      branches:  [main]
      paths:
        - 'solver/**'
  jobs:
    deploy:
      runs-on: ubuntu-22.04
      defaults:
        run:
          working-directory: ./solver
      steps:
        - uses: actions/checkout@v3
        - uses: dtolnay/rust-toolchain@stable
        - run: cargo build
