  on:
    push:
      branches: [main]
      paths:
        - 'webapp/svelte/**'
        - '.github/workflows/webapp-build.yml'
    pull_request:
      branches:  [main]
      paths:
        - 'webapp/svelte/**'
        - '.github/workflows/webapp-build.yml'
  jobs:
    build:
      runs-on: ubuntu-22.04
      if: github.event == 'pull_request' 
      defaults:
        run:
          working-directory: ./webapp/svelte
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js v20
          uses: actions/setup-node@v3
          with:
            node-version: 20
        - uses: dtolnay/rust-toolchain@stable
        - uses: Swatinem/rust-cache@v2
          with:
            workspaces: |
              ./webapp/svelte/wasm-sample
        - run: cargo install wasm-pack
        - run: make

    test-gcp-login:
      runs-on: ubuntu-22.04
      defaults:
        run:
          working-directory: ./webapp/svelte
      steps:
        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v1'
          with:
            workload_identity_provider: projects/558692735371/locations/global/workloadIdentityPools/my-pool/providers/my-provider
            service_account: 'github-actions@my-project.iam.gserviceaccount.com'
