  on:
    push:
      branches: [main]
      paths:
        - 'webapp/svelte/**'
    pull_request:
      branches:  [main]
      paths:
        - 'webapp/svelte/**'
        - '.github/workflows/webapp-build.yml'
  jobs:
    deploy:
      runs-on: ubuntu-22.04
      defaults:
        run:
          working-directory: ./webapp/svelte
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js v20
          uses: actions/setup-node@v3
          with:
            node-version: 20
        - uses: dtolnay/rust-toolchain@stable
        - uses: Swatinem/rust-cache@v2
          with:
            workspaces: |
              ./webapp/svelte/wasm-sample
        - run: cargo install wasm-pack
        - run: make
